title: Freshify
description: A support hub for Freshify
theme: just-the-docs

url: https://support.freshifynet.com

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2024 Freshify. If you come across any inappropriate uses of our documentation, report them to a leadership member on our Discord server."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

color_scheme: dark

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

favicon_ico: "/assets/images/favicon.ico"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External navigation links
nav_external_links:
  - title: Freshify on GitHub
    url: https://github.com/sa1ntslovur/freshify
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false


# For copy button on code
enable_copy_code_button: true

aux_links:
  Roblox Group: https://www.roblox.com/groups/9018942/Freshify#!/about
  Discord Server: https://discord.gg/8PYF7MUBNr
  Supermarket: https://www.roblox.com/games/16105101085/Freshify-Supermarket
  Training Center: https://www.roblox.com/games/16031863551/Training-Center


collections:
  guides:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    guides:
      name: Guides
